### ISSUE TITLE
UCRC Inventory Survey - Editing records 

### ISSUE THREAD

**Issue by klcummings** [UGS-GIS/UCRC---Survey-123#4]
### What type of GIS Support?

Data collection app

### Describe the support you requested.

When working the in the Survey 123 web application, we are unable to edit records created by another user. Also, we can't edit existing records on the IPad. 

### When is this GIS support needed by...

11/1/2022

### How Urgent is this?

Medium

### Please list Project Code to charge time.

UEXO

**Comment by marthajensen** [comment]
Do you mind checking this again? I think you should have permission to edit the records now.

**Comment by klcummings** [comment]
Thanks so much for all of your help, Martha! I checked My Surveys, and the UCRC Inventory Survey doesn't show up in my survey list.

**Comment by marthajensen** [comment]
Katie - I changed the ownership of all the layers. You should now be able to edit in the Survey 123 web app. However, ESRI made it so that only the owner of the data can edit in the web app so if you want Skadi to edit in the web app, she will need to login  as you. Skadi can still edit in the Inbox on the Ipad or on the Survey 123 Desktop app Inbox.

**Comment by marthajensen** [comment]
Hi Katie - I had to transfer ownership of the layers back to myself so that I could share them with ESRI support. The ESRI support may have figured out a way to sideload your entire geodatabase to an IPAD. Therefore, you won't be able to edit the Survey in the web app, since I am now the owner of the layers again. I'll let you know how it goes with ESRI, and afterwards I'll change the layer ownership back to you.
